version: '3.8'

services:
  webapp:
    build: ./webapp
    ports:
      - "8080:80"
    restart: always

  pythonapp:
    build: ./pythonapp
    ports:
      - "5050:5000"
    restart: always